### ISSUE TITLE
No `src` directory in package  installed by commend `npm i node-summarizer `

### ISSUE THREAD

**Issue by tijax1024** [SwapnikKatkoori/Text-Summarizer#1]
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './src/SummarizerManager'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/breakeris/Project/my_blog/node_modules/node-summarizer/index.js:1:98)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by SwapnikKatkoori** [comment]
Hi, so sorry about that. Thanks for bringing it to my attention. It should be fixed now.
